  
server:
  port: 9527 #8181
  servlet:
    context-path: /
spring:
  application:
    name: microservice-provider-user
  datasource:
    #url: jdbc:mysql://localhost:3306/zentao?characterEncoding=UTF-8
    url: jdbc:mysql://127.0.0.1:3306/zhl?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ruiyun
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0  
    host: 127.0.0.1
    port: 6379  
    password:   
    timeout: 0 
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
  kafka:
    #bootstrap-servers: 192.168.1.254:9092
    #bootstrap-servers: 127.0.0.1:9092
    bootstrap-servers: 101.37.30.10:9091
    consumer: 
      group-id: ruiyunKeywords
    template:
      default-topic: ruiyun-keywords-task
    listener:
      concurrency: 3
    producer:
      group-id: ruiyunItemCopy
      batch-size: 1000
  
ruiyun:
  login_platform_name: JD
  app_id: 2253C69797063D04627C8D499CD3F5A4
  app_secret: 8151c70adae64a15a43d6aaf4602c122
  auth_url: https://oauth.jd.com/oauth/authorize
  token_url: https://oauth.jd.com/oauth/token
  resp_url: /
  login_url: /login
  view: web
  response_type: code
  redirect_uri: /auth
  redirect_result_uri: /auth
  state: 1234
  extend_prop: 5
  grant_type: authorization_code
  need_filter_url: /itemcopy/task/search,/itemcopy/item-manage/list,/itemcopy/item-select/list/search,/itemcopy/item-select/list/search/pageInfo,/itemcopy/item-select/copyitems,/itemcopy/item-select/itemcategory
 
 

mybatis:
  mapperLocations: classpath*:/**/mappers/*mapper.xml  